query topic($publicationId: Int!, $pageId: Int!) {
	ishTopic(publicationId: $publicationId, itemId: $pageId) {
        ...ItemFields  
		url
		xhtml
        abstract {
          title
		  type
		  xhtml
          links {
            cmUri
            title
            type
            uri
          }
        }
        relatedLinks {
          links {
            cmUri
            title
            type
            uri
          }
		  xhtml
        }
		...on IshConceptTopic {
		  body {
			xhtml
			sections {
			  type
			  xhtml
			}
		  }		  
		}  
		...on IshGenericTopic {
		  body {
			xhtml
			sections {
			  type
			  xhtml
			}
		  }
		}       

	}
}