<#
.SYNOPSIS
    Copies the Example WebApp Dockerfile (net8 or net10), points Discovery at a CM/CD IP,
    then builds the image from the repo root if DXA runtime ports are open.
    The generated Dockerfile is gitignored and must not be committed.

.PARAMETER Framework
    Target TFM Dockerfile: net8 (Dockerfile) or net10 (Dockerfile.net10.0).

.PARAMETER CmServerIp
    IPv4 or IPv6 address of the combined CM/CD host (not a hostname).

.EXAMPLE
    .\test\New-CmTestDockerfile.ps1 -Framework net8 -CmServerIp 192.0.2.10

.EXAMPLE
    .\test\New-CmTestDockerfile.ps1 -Framework net10 -CmServerIp 192.0.2.10
#>
[CmdletBinding()]
param(
    [ValidateSet('net8', 'net10')]
    [string]$Framework,

    [Parameter(Mandatory = $true)]
    [string]$CmServerIp
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot

$frameworkValues = @('net8', 'net10')
if ([string]::IsNullOrWhiteSpace($Framework)) {
    Write-Host ("Available Framework values: {0}" -f ($frameworkValues -join ', ')) -ForegroundColor Cyan
    $Framework = Read-Host 'Framework'
}
if ($frameworkValues -notcontains $Framework) {
    throw ("Framework must be one of: {0}. Got: '{1}'" -f ($frameworkValues -join ', '), $Framework)
}

$parsedIp = $null
if (-not [System.Net.IPAddress]::TryParse($CmServerIp, [ref]$parsedIp)) {
    throw "CmServerIp must be an IP address. Got: '$CmServerIp'"
}

$testPorts = Join-Path $PSScriptRoot 'Test-DxaRuntimePorts.ps1'
Write-Host "Checking DXA runtime ports..." -ForegroundColor Cyan
$runtimePortsOpen = & $testPorts -CmServerIp $CmServerIp -DxaRuntimeOnly -PassThru
if (-not $runtimePortsOpen) {
    Write-Host "Skipping docker build because DXA runtime ports are not open." -ForegroundColor Red
    exit 1
}

$webAppDir = Join-Path $RepoRoot 'dxa-web-application-mvc-net/dotnet/src/Tridion.Dxa.Example.WebApp'
$discoveryUrl = "http://${CmServerIp}:8082/discovery.svc"
$appsettingsRel = 'dxa-web-application-mvc-net/dotnet/src/Tridion.Dxa.Example.WebApp/appsettings.json'

if ($Framework -eq 'net8') {
    $sourceName = 'Dockerfile'
    $destName = 'Dockerfile.cmtest'
    $imageTag = 'dxa-example-webapp:net8-cmtest'
}
else {
    $sourceName = 'Dockerfile.net10.0'
    $destName = 'Dockerfile.net10.0.cmtest'
    $imageTag = 'dxa-example-webapp:net10-cmtest'
}

$sourcePath = Join-Path $webAppDir $sourceName
$destPath = Join-Path $webAppDir $destName

if (-not (Test-Path -LiteralPath $sourcePath)) {
    throw "Source Dockerfile not found: $sourcePath"
}

$content = Get-Content -LiteralPath $sourcePath -Raw

$generatedHeader = @"
# GENERATED by New-CmTestDockerfile.ps1 — do not commit
# Build from repo root:
#   docker build -f dxa-web-application-mvc-net/dotnet/src/Tridion.Dxa.Example.WebApp/$destName -t $imageTag .

"@

$copyNeedle = "COPY dxa-web-application-mvc-net/dotnet/src/Tridion.Dxa.Example.WebApp/ ./dxa-web-application-mvc-net/dotnet/src/Tridion.Dxa.Example.WebApp/"
$sedInsert = @"
$copyNeedle

# Point Discovery at the CM/CD test host (replaces localhost in appsettings.json)
RUN sed -i 's#http://localhost:8082/discovery.svc#$discoveryUrl#g' $appsettingsRel
"@

if ($content -notlike "*$copyNeedle*") {
    throw "Unexpected Dockerfile layout; could not find WebApp COPY line in $sourceName"
}

$content = $content.Replace($copyNeedle, $sedInsert)

$envNeedle = "ENV Logging__LogLevel__Default=Warning"
$envInsert = @"
$envNeedle
ENV Dxa__Services__Discovery=$discoveryUrl
"@

if ($content -notlike "*$envNeedle*") {
    throw "Unexpected Dockerfile layout; could not find Logging ENV in $sourceName"
}

$content = $content.Replace($envNeedle, $envInsert)

# Drop the original "Build from repo root" comment block; generated header replaces it.
$content = $content -replace '(?s)^# Build from repo root:.*?(?=# Use official)', ''

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($destPath, $generatedHeader + $content.TrimStart(), $utf8NoBom)

Write-Host "Wrote $destPath" -ForegroundColor Green
Write-Host "Discovery: $discoveryUrl"
Write-Host ""

$dockerFileRel = "dxa-web-application-mvc-net/dotnet/src/Tridion.Dxa.Example.WebApp/$destName"
Write-Host "Running docker build from repo root..." -ForegroundColor Cyan
Write-Host "  docker build -f $dockerFileRel -t $imageTag ."

Push-Location $RepoRoot
try {
    & docker build -f $dockerFileRel -t $imageTag .
    if ($LASTEXITCODE -ne 0) {
        throw "docker build failed with exit code $LASTEXITCODE"
    }
}
finally {
    Pop-Location
}

Write-Host "Image tagged $imageTag" -ForegroundColor Green
